add_newline = false

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[✖](bold red)"
vicmd_symbol = "[❯](bold yellow)"
use_symbol_for_status = true

[cmd_duration]
min_time = 5_000

[git_state]
cherry_pick = "🍒 PICKING"

[nodejs]
disabled = true

[package]
disabled = true

[aws]
disabled = true

[golang]
disabled = false

[battery]
charging_symbol = '⚡'
discharging_symbol = '🔋'
